export const API = {
    // baseUri: 'http://pte.novasoftware.com.au:3060/',
    baseUri: 'http://localhost:3003/',
    // baseUri: 'http://iregiester.novasoftware.com.au:3060/',
    initPosts: 'api/restaurants',
    getallTables: 'api/getAllTables',
    getAllDishes: 'api/getAllDishes',
    neworder: 'neworder',
    checkOut: 'checkout',
    getModDishes: 'api1/getModDishes',
    getTableDishes: 'api1/getTableDishes',
    modDish: 'modDish',
    getModDish: 'api1/getModDish',
    getOrderComment: 'api1/getOrderComment',
    addDish: 'addDish',
    getDeliveryOrders: 'api/getDeliveryOrders',
    getAllOrders: 'api/getAllOrders',
    deleteModDish: 'deleteModDish',
    BookTable: 'api1/BookTable',
    CancleBookTable: 'api1/CancleBookTable',
    getDeliveryOrderDetails: "api1/getDeliveryOrderDetails",
    CompleteDeliveryOrder: 'api1/CompleteDeliveryOrder',
    getDeliveryOrderDetailswithOrder: 'api1/getDeliveryOrderDetailswithOrder',
    pointsInfo: 'pointsInfo',
    redeem: 'redeem'

}
