export const API = {
    // baseUri: 'http://pte.novasoftware.com.au:3060/',
    // baseUri: 'http://localhost:3060/',
    // baseUri: 'http://iregiester.novasoftware.com.au:3060/',
    baseUri: 'http://api.shuweiyuan.com.au/',
    initPosts: 'api/restaurants',
    getallTables: 'api/getAllTables',
    getAllDishes: 'api/getAllDishes',
    neworder: 'neworder',
    checkOut: 'checkout',
    getModDishes: 'api1/getModDishes',
    getTableDishes: 'api1/getTableDishes',
    modDish: 'modDish',
    getModDish: 'api1/getModDish',
    getOrderComment: 'api1/getOrderComment',
    addDish: 'addDish',
    getDeliveryOrders: 'api/getDeliveryOrders',
    getAllOrders: 'api/getAllOrders',
    deleteModDish: 'deleteModDish',
    BookTable: 'api1/BookTable',
    CancleBookTable: 'api1/CancleBookTable',
    getDeliveryOrderDetails: "api1/getDeliveryOrderDetails",
    CompleteDeliveryOrder: 'api1/CompleteDeliveryOrder',
    getDeliveryOrderDetailswithOrder: 'api1/getDeliveryOrderDetailswithOrder',
    pointsInfo: 'pointsInfo',
    redeem: 'redeem',
    getCurrentTime: 'getCurrentTime',
    getOrderDishes2: 'api1/getOrderDishes2',
    getModDishesByOrderID: 'api1/getModDishesByOrderID',
    updateOriginDeleted: 'api1/updateOriginDeleted',
    updateModifiedDeleted: 'api1/updateModifiedDeleted',
    Bookingneworder: 'Bookingneworder',
    getBookingTableDishes: 'api1/getBookingTableDishes',
    getOrderBookingDetailsbyTableID: 'api1/getOrderBookingDetailsbyTableID',
    InheritBookingDishes: 'api1/InheritBookingDishes',
    updateDishInfo: 'updateDishInfo',
    UnavailableDish: 'api1/UnavailableDish',
    AvailableDish: 'api1/AvailableDish',
    addNewDishInfo: 'addNewDishInfo',
    deleteDishInfo: 'api1/deleteDishInfo',
    deleteImage: 'api1/deleteImage',
    login: 'users/userlogin',
    printReceipt: 'printReceipt ',
    KprinterN: 'KprinterN',
    KprinterS: 'KprinterS ',
    KprinterF: 'KprinterF ',
    logout: 'users/logout ',

}
